#include "../include/debug.h"
// TokenType values in strings for debugging
static const char* const token_names[] = {
  [TOKEN_IDENTIFIER]      = "IDENTIFIER",
  [TOKEN_DIGIT]           = "DIGIT",
  [TOKEN_INTEGER_LITERAL] = "INTEGER LITERAL",
  [TOKEN_DOUBLE_LITERAL]  = "DOUBLE LITERAL",
  [TOKEN_STRING_LITERAL]  = "STRING LITERAL",
  [TOKEN_CHAR_LITERAL]    = "CHAR LITERAL",
  [TOKEN_LETTER]          = "LETTER",
  [TOKEN_ERROR]           = "ERROR",
  [TOKEN_EOF]             = "EOF",
  [TOKEN_AUTO]     = "AUTO",     [TOKEN_BREAK]    = "BREAK",
  [TOKEN_CASE]     = "CASE",     [TOKEN_CHAR]     = "CHAR",
  [TOKEN_CONST]    = "CONST",    [TOKEN_CONTINUE] = "CONTINUE",
  [TOKEN_DEFAULT]  = "DEFAULT",  [TOKEN_DO]       = "DO",
  [TOKEN_DOUBLE]   = "DOUBLE",   [TOKEN_ELSE]     = "ELSE",
  [TOKEN_ENUM]     = "ENUM",     [TOKEN_EXTERN]   = "EXTERN",
  [TOKEN_FLOAT]    = "FLOAT",    [TOKEN_FOR]      = "FOR",
  [TOKEN_GOTO]     = "GOTO",     [TOKEN_IF]       = "IF",
  [TOKEN_INT]      = "INT",      [TOKEN_LONG]     = "LONG",
  [TOKEN_REGISTER] = "REGISTER", [TOKEN_RETURN]   = "RETURN",
  [TOKEN_SHORT]    = "SHORT",    [TOKEN_SIGNED]   = "SIGNED",
  [TOKEN_SIZEOF]   = "SIZEOF",   [TOKEN_STATIC]   = "STATIC",
  [TOKEN_STRUCT]   = "STRUCT",   [TOKEN_SWITCH]   = "SWITCH",
  [TOKEN_TYPEDEF]  = "TYPEDEF",  [TOKEN_UNION]    = "UNION",
  [TOKEN_UNSIGNED] = "UNSIGNED", [TOKEN_VOID]     = "VOID",
  [TOKEN_VOLATILE] = "VOLATILE", [TOKEN_WHILE]    = "WHILE",
  [TOKEN_INCLUDE] = "INCLUDE",
  [TOKEN_LEFT_PAREN]    = "LEFT_PAREN",    [TOKEN_RIGHT_PAREN]   = "RIGHT_PAREN",
  [TOKEN_LEFT_BRACE]    = "LEFT_BRACE",    [TOKEN_RIGHT_BRACE]   = "RIGHT_BRACE",
  [TOKEN_LEFT_BRACKET]  = "LEFT_BRACKET",  [TOKEN_RIGHT_BRACKET] = "RIGHT_BRACKET",
  [TOKEN_COMMA]         = "COMMA",         [TOKEN_DOT]           = "DOT",
  [TOKEN_MINUS]         = "MINUS",         [TOKEN_PLUS]          = "PLUS",
  [TOKEN_MINUS_MINUS]   = "MINUS MINUS",   [TOKEN_PLUS_PLUS]     = "PLUS PLUS",
  [TOKEN_MINUS_EQUAL]   = "MINUS EQUAL",   [TOKEN_PLUS_EQUAL]    = "PLUS EQUAL",
  [TOKEN_MUL]           = "MUL",           [TOKEN_DIV]           = "DIV",
  [TOKEN_MUL_EQUAL]     = "MUL EQUAL",     [TOKEN_DIV_EQUAL]     = "DIV EQUAL",
  [TOKEN_MOD]           = "MOD",           [TOKEN_MOD_EQUAL]     = "MOD EQUAL",
  [TOKEN_SEMICOLON]     = "SEMICOLON",
  [TOKEN_COLON]         = "COLON",         [TOKEN_QUESTION]      = "QUESTION",
  [TOKEN_NOT_EQUAL]     = "NOT_EQUAL",     [TOKEN_NOT]           = "NOT",
  [TOKEN_EQUAL_EQUAL]   = "EQUAL_EQUAL",   [TOKEN_EQUAL]         = "EQUAL",
  [TOKEN_LESS_EQUAL]    = "LESS_EQUAL",    [TOKEN_LESS]          = "LESS",
  [TOKEN_GREATER_EQUAL] = "GREATER_EQUAL", [TOKEN_GREATER]       = "GREATER",
  [TOKEN_AND]           = "AND",           [TOKEN_OR]            = "OR",
  [TOKEN_TAG]           = "TAG",
  [TOKEN_MEMBER]        = "MEMBER",
  [TOKEN_LSE]           = "LSE",           [TOKEN_RSE]           = "RSE",
  [TOKEN_AND_BITW_EQUAL]= "AND_BITW_EQUAL",[TOKEN_OR_BITW_EQUAL] = "OR_BITW_EQUAL",
  [TOKEN_XOR_BITW_EQUAL]= "XOR_BITW_EQUAL",
  [TOKEN_AND_BITW]      = "AND_BITW",      [TOKEN_OR_BITW]       = "OR_BITW",
  [TOKEN_NOT_BITW]      = "NOT_BITW",      [TOKEN_XOR_BITW]      = "XOR_BITW",
  [TOKEN_LEFT_SHIFT]    = "LEFT_SHIFT",    [TOKEN_RIGHT_SHIFT]   = "RIGHT_SHIFT",
  [TOKEN_LIB]           = "LIB",
};
const char* token_type_name(TokenType type) {
  return token_names[type];
}
